name: CI/CD for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Tag Docker Image
    - name: Build Docker Image
      run: |
        IMAGE_NAME=shgiri/job-portal-fe
        IMAGE_TAG=${{ github.sha }}
        docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

    # Push Docker Image to Docker Hub
    - name: Push Docker Image
      run: |
        IMAGE_NAME=shgiri/job-portal-fe
        IMAGE_TAG=${{ github.sha }}
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
